### ISSUE TITLE
Getting {"running": false} on curl GET operation

### ISSUE THREAD

**Issue by Ke1i** [manuels/nebula-lighthouse-service#4]
First of all, thanks for setting this up for folks like myself to tinker with.

So..
This is the command I used:

`curl -X POST "http://203.18.30.196/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse.crt -F host_key=@./lighthouse.key`

Which gets me a `{"port":49168}` output. But when I try `curl -X GET "http://203.18.30.196/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse.crt -F host_key=@./lighthouse.key` I get `{"running": false}`

When I look at the status of the nebula service, I see a lot of "Handshake timed out" messages.
I've tried both of the provided public lighthouses.
Did something change?

**Comment by bloominstrong** [comment]
Looking at the logs the port 49168 service on 203.18.30.196 seem to be related to the ca.
```msg="Invalid certificate from host"  ... error="certificate validation failed: could not find ca for the certificate"```

Looking back further it looks like the POST was run several times, the README says this is fine but it's the only thing I can see as this server is otherwise regularly used by a number of client.
Looking further back I can see another user appeared to be suffering from the same issue as there are lots of similar logs and I can see similar behavior in the logs, the port both ports and a few others are also is tied to 192.0.2.1/24 range much earlier in the logs.

Restarting the public lighthouse service appears to have fixed it as I can see handshakes associated with that port happening now.

**Comment by Ke1i** [comment]
Thanks for looking into it, it's working now.

**Comment by manuels** [comment]
@bloominstrong Great catch, do you know how we could prevent this in the future?

**Comment by bloominstrong** [comment]
@manuels Short answer, I'm not sure what has caused it yet.

All I can tell so far is that for some reason the port was already running a nebula process with the a 192.0.2.1/24 network before the user sent their first POST, the nebula-lighthouse-service.webservice accepted the POST and wrote out the new config (assumingly replacing the 192.0.2.1/24 one) but because a process was already listening on that port the new process could not run (and reloading is not fully supported in nebula yet).

See https://github.com/manuels/nebula-lighthouse-service/issues/4#issuecomment-1872450760
<s>So the question is where the 192.0.2.1/24 config came from, it looks like there have been 4 instances of it on 203.18.30.196 and 2 of those will effect the next two users who try to start using the server
```
Dec 27 21:49:32 element-china nebula-lighthouse-service.webservice[856]: time="2023-12-27T21:49:32+10:00" level=info msg="Nebula interface is active" build= interface=disabled network=192.0.2.1/24 udpAddr="0.0.0.0:49169"
Dec 27 21:49:32 element-china nebula-lighthouse-service.webservice[854]: time="2023-12-27T21:49:32+10:00" level=info msg="Nebula interface is active" build= interface=disabled network=192.0.2.1/24 udpAddr="0.0.0.0:49170"
```
I did previously go and alter the config for the process that I personally use to change the cipher and may have removed an initial test but I don't see how that could cause these 4 and the issue reports problem with both servers.

@manuels if you run the below as root on 46.38.232.184 do you get any of this weird range running?
``` journalctl -u snap.nebula-lighthouse-service.webservice.service --boot --grep 192.0.2.1/24 ```
And if you remove the boot option do any of the logs show it?
``` journalctl -u snap.nebula-lighthouse-service.webservice.service --grep 192.0.2.1/24 ```</s>

I will try to do a bit more poking around but don't have too much time available at the moment.

**Comment by Ke1i** [comment]
@manuels, @bloominstrong Slightly off topic but if there's anyone to ask this, it's you guys.
What do you use for Android? The official Nebula client keeps crashing for me.

**Comment by bloominstrong** [comment]
I don't use nebula on Android at the moment funnily enough (used it a little bit without any issues), It's still on OpenVPN on Android mainly because I can push the DNS, DNS on Linux is doable so my laptop has switched over but until most my services are on nebula it does not really matter and 90% of my stuff is on one network so nebula is not doing a whole lot from a resiliency perspective either.

**Comment by bloominstrong** [comment]
Ok so the 192.0.2.1/24 addresses appear to just be one user testing with a few different certificate (192.0.2.0/24 is actually a range reserved for documentation under).

The problem is it is allocating a already in use port to a new user when they send their POST. This is calculated by ``` min_port + len(nebula_lighthouses) ``` but if there is a problem starting a lighthouse service at start up ``` len(nebula_lighthouses) ``` will e different to the actual number of lighthouse services configured
```
# ps aux |grep /var/snap/nebula-lighthouse-service/common/config/lighthouse- |wc -l
17
# ls -l /var/snap/nebula-lighthouse-service/common/config/lighthouse-* |wc -l
23
```

so we need to change how we are calculating the next port to use as the current method does not seem to take into account
configuration files that exist but are somehow invalid and configuration files that make nebula exit or crash (expired cert or ca).

**Comment by aydintb** [comment]
Thanks for this beautiful service.  
My setup seems to got the same problem.

Best regards.  

```bash
curl -X POST "http://203.18.30.196/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse1.crt -F host_key=@./lighthouse1.key
```

{"port":49168}%  
```bash
curl -X GET "http://203.18.30.196/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse1.crt -F host_key=@./lighthouse1.key
```
{"running":false}%  


also

```bash
curl -X POST "http://46.38.232.184:9999/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse2.crt -F host_key=@./lighthouse2.key
```
{"port":49162}% 

```bash
curl -X GET "http://46.38.232.184:9999/lighthouse/" -F ca_crt=@./ca.crt -F host_crt=@./lighthouse2.crt -F host_key=@./lighthouse2.key
```
{"running":false}%

**Comment by bloominstrong** [comment]
That's the same port as @Ke1i which makes sense as a new service is not getting added but an existing one replaced so the next port to assign is always the same.

So adding new users is broken, I will try to write a fix tomorrow.

**Comment by Ke1i** [comment]
Yeah, that's the port I'm currently using ;)

![Screenshot_20231231-191621_ConnectBot](https://github.com/manuels/nebula-lighthouse-service/assets/20503185/e56b4261-4ccf-4ea6-b8f7-724c21459f05)

**Comment by aydintb** [comment]
still having the same error!

**Comment by bloominstrong** [comment]
@aydintb, @Ke1i , FYI you will want to do your POST again for 203.18.30.196 as I just updated (it was on the stable channel but the fix was pushed to edge). This is because it was writing over to config for port 49168 one of you will probably end up with that port and the other will get a new port.

**Comment by aydintb** [comment]
{"running":true,"port":49168} 

Works, thanks..
